library("shiny")
library("foreign")
library(shiny)
library(htmlwidgets)
#library(D3TableFilter)
library(rhandsontable)
library(DT)
#library(shinydashboard)
library(leaflet)
library(shinyjs)
#library(googlesheets)
library(ggplot2)
library(dplyr)
library(scales)
library(shinyFiles)
library(tidyverse)
library(readxl)

predictValues <- NULL